---
apiVersion: v1
kind: Service
metadata:
  name: bitwarden
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 3012
    targetPort: 3012
    protocol: TCP
    name: websocket
  selector:
    app: bitwarden
