apiVersion: apps/v1
kind: Deployment
metadata:
  name: haste-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haste-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: haste-server
    spec:
      nodeSelector:
        node-role.k8s.domain.tld/general: "true"
      hostname: haste-server
      restartPolicy: Always
      containers:
      - name: haste-server
        image: dirtycajunrice/haste-server
        imagePullPolicy: Always
        ports:
          - containerPort: 7777
        envFrom:
          - configMapRef:
              name: haste-server-env
        livenessProbe:
          failureThreshold: 10000
          httpGet:
            path: /
            port: 7777
        volumeMounts:
          - mountPath: /config/data
            name: haste-server-data-volume
          - mountPath: /app
            name: haste-server-app-volume
      volumes:
        - name: haste-server-data-volume
          nfs:
            server: 192.168.1.123
            path: /mnt/nfs/haste-server/data
        - name: haste-server-app-volume
          nfs:
            server: 192.168.1.123
            path: /mnt/nfs/haste-server/app
