apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  namespace: domain-tlx
data:
  influxdb.conf: |
    [meta]
      dir = "/var/lib/influxdb/meta"
    [data]
      dir = "/var/lib/influxdb/data"
      wal-dir = "/var/lib/influxdb/wal"
    [coordinator]
    [retention]
    [shard-precreation]
    [monitor]
    [http]
       enabled = true
       bind-address = ":8086"
    [logging]
    [subscriber]
    [[graphite]]
    [[collectd]]
    [[opentsdb]]
    [[udp]]
    [continuous_queries]
    [tls]

